# Dependencies
markdown:           redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments:           true

# Permalinks
permalink:          pretty

# Server
host:               0.0.0.0
port:               9001
baseurl:            /
url:                http://localhost:9001
encoding:           UTF-8

# the excluded directoies
exclude:            []

# site information
info:
  site_name:        Cube-PHP

meta:
  description:      "简单的php框架"
  keywords:         "Cube PHP, 简单的php框架"
  author:           "liaohuqiu@gmail.com"

# multiple language
language_default:   'cn'

languages:          ["cn", "en"]

# left navigation
left_nav:
  cn:
    title:          Cube PHP
    path:           /
    items:
      - path:       /code-style
        title:      "规范和约定"
      - path:       /router
        title:      "路由"
      - path:       /app
        title:      "处理请求"
      - path:       /db
        title:      "数据库操作"

# right navigation
right_nav:
  - title:          Fork on Github
    url:            https://github.com/liaohuqiu/cube-php

# analytics account information, remember to change this.
analytics:
  google:
    account:         UA-43024238-7
